name: Deploy to S3

on:
  push:
    branches:
      - main # Or specify any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Specify your region

      # Sync the code to the S3 bucket
      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://dynamic-site-test --delete --exact-timestamps

      # Optional: Invalidate CloudFront cache (if using CloudFront with S3)
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
