name: Deploy to S3

on:
  push:
    branches:
      - main # Trigger on push to main branch
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: "Deployment environment (e.g., production)"
        required: false
        default: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js packages
        run: npm install

      - name: Run Node.js build
        run: npm run build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust based on your AWS region

      - name: Deploy to S3
        run: |
          aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --delete
          aws s3 sync ./.next s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --exclude='*' --include='routes-manifest.json'
